### ISSUE TITLE
Console spam and emoji compontent

### ISSUE THREAD

**Issue by quiquelhappy** [DCsunset/vuetify-markdown-editor#1]
![spam while typing and unstyled emoji picker](https://i.imgur.com/DkVmhTe.png)
(spam while typing and unstyled emoji picker)

**Comment by DCsunset** [comment]
The spam now is removed in v1.3.0.

But I haven't encountered the unstyled emoji picker.
It might be the problem of network connection
since non-native emojis are loaded from CDN.

If it's not the problem, could you give an example to reproduce it?

**Comment by DCsunset** [comment]
Close due to inactivity. Feel free to open it again the problem exists.
