### ISSUE TITLE
Cannot find module '../src/util/types' or its corresponding type declarations.

### ISSUE THREAD

**Issue by bqsgwys** [DCsunset/vuetify-markdown-editor#10]
Cannot find module '../src/util/types' or its corresponding type declarations.
```
      1 | import Vue from 'vue'
      2 | import MarkdownIt from 'markdown-it';
  > 3 | import { Config } from '../src/util/types';
```

it seems while compiling and packing typescript to npm package, the util/types has gone

**Comment by DCsunset** [comment]
Thanks for your feedback. I have added the missing files in v3.2.1.
I hope it could fix this problem.
