### ISSUE TITLE
What about adding table?

### ISSUE THREAD

**Issue by leodahal4** [DCsunset/vuetify-markdown-editor#16]
Can we make this component render table while text on md file is,
| Command | Description |
|-------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------|
| hydra -P password-file.txt -v $ip snmp                                                                                                    | Hydra brute force against SNMP                       |

And this would lead to a simple table??

**Comment by DCsunset** [comment]
I have fixed the style of the table in v3.3.2.
Now the table should look better than before.
