### ISSUE TITLE
About a glitch and a request

### ISSUE THREAD

**Issue by tpircsnarT** [DCsunset/vuetify-markdown-editor#8]
glitch is:
![1](https://user-images.githubusercontent.com/16444353/83587525-e46e0080-a581-11ea-840a-42f8400b649b.jpg)

the width of editor get reduced.

request:
could you add a prop for words counter and an event if the words is out of limits, would emit an event?

**Comment by DCsunset** [comment]
Hello, it's a good suggestion to add a counter for the input. I've added it as an optional prop in the master branch.
However, I think it would be easier to check whether the input is out of limits outside the component, say, watching the variable.

As for the glitch, I couldn't reproduce it on my computer. Could you provide more information, such as the browser or the console log of the browser?

**Comment by tpircsnarT** [comment]
the glitch is appeared in some cases:
As I use my PC to develop, it is fine.
When it goes to deployment on my company's console,
my PC browser appeared this glitch and my boss' laptop doesn't.
Just take it as notice.

**Comment by DCsunset** [comment]
I've tested the release version on my PC using both Chrome and Firefox but still couldn't reproduce it. Maybe you could provide some info about the release version, the browser version, and the log of the browser to help solve it.

**Comment by jkpark** [comment]
this issue apears in Vuetify version 2.6.0
![image](https://user-images.githubusercontent.com/1896404/162911602-b85dd132-c0b8-4d57-9e2c-e89d6d5f7c44.png)

my `package-lock.json`
```
"packages": {
    "": {
      "name": "my-app",
      "version": "0.1.0",
      "dependencies": {
        "core-js": "^3.8.3",
        "vue": "^2.6.14",
        "vue-router": "^3.5.1",
        "vuetify": "^2.6.0",
        "vuetify-markdown-editor": "^3.3.3",
        "vuex": "^3.6.2"
      },
```


`MdTest.Vue`
```
<template>
  <div>
    
    <Editor v-model="tcData" />
  </div>
</template>

<script>
import { Editor } from "vuetify-markdown-editor";

export default {
  name: 'MdTest',
  components: {
    Editor,
  },
  data() {
    return {
      tcData: "",
    };
  },
}
</script>
```
